-- ROLE_CATEGORY
INSERT INTO "ROLE_CATEGORY"(ID, NAME) 
VALUES(ROLE_CATEGORY_ID_SEQ.NEXTVAL, 'all');

INSERT INTO "ROLE_CATEGORY"(ID, NAME) 
VALUES(ROLE_CATEGORY_ID_SEQ.NEXTVAL, 'member');

INSERT INTO "ROLE_CATEGORY"(ID, NAME) 
VALUES(ROLE_CATEGORY_ID_SEQ.NEXTVAL, 'project');

INSERT INTO "ROLE_CATEGORY"(ID, NAME) 
VALUES(ROLE_CATEGORY_ID_SEQ.NEXTVAL, 'notice');

INSERT INTO "ROLE_CATEGORY"(ID, NAME) 
VALUES(ROLE_CATEGORY_ID_SEQ.NEXTVAL, 'faq');

-- MEMBER - ID: admin, PW: admin
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'admin@admin.com', 'admin', '$2a$10$GCfK98O7Pn5frUh76Cpu4uSEd33a6Ghr6KUZtcg7d18I0EAEbiy9C', 'Y');
-- MEMBER - ID: subadmin, PW: admin
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'subadmin@admin.com', 'admin', '$2a$10$GCfK98O7Pn5frUh76Cpu4uSEd33a6Ghr6KUZtcg7d18I0EAEbiy9C', 'Y');
-- MEMBER - ID: memberadmin, PW: admin
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'memberadmin@admin.com', 'admin', '$2a$10$GCfK98O7Pn5frUh76Cpu4uSEd33a6Ghr6KUZtcg7d18I0EAEbiy9C', 'Y');

-- MEMBER - ADMIN ROLE_CATEGORY
INSERT INTO "MEMBER_ROLE_CATEGORY"(MEMBER_ID, ROLE_CATEGORY_ID) 
VALUES(
    (SELECT ID FROM "MEMBER" WHERE EMAIL = 'admin@admin.com'), 
    (SELECT ID FROM "ROLE_CATEGORY" WHERE NAME = 'all')
);

INSERT INTO "MEMBER_ROLE_CATEGORY"(MEMBER_ID, ROLE_CATEGORY_ID) 
VALUES(
    (SELECT ID FROM "MEMBER" WHERE EMAIL = 'subadmin@admin.com'), 
    (SELECT ID FROM "ROLE_CATEGORY" WHERE NAME = 'notice')
);

INSERT INTO "MEMBER_ROLE_CATEGORY"(MEMBER_ID, ROLE_CATEGORY_ID) 
VALUES(
    (SELECT ID FROM "MEMBER" WHERE EMAIL = 'subadmin@admin.com'), 
    (SELECT ID FROM "ROLE_CATEGORY" WHERE NAME = 'faq')
);

INSERT INTO "MEMBER_ROLE_CATEGORY"(MEMBER_ID, ROLE_CATEGORY_ID) 
VALUES(
    (SELECT ID FROM "MEMBER" WHERE EMAIL = 'memberadmin@admin.com'), 
    (SELECT ID FROM "ROLE_CATEGORY" WHERE NAME = 'member')
);

-- COMMIT
COMMIT;