
-- MEMBER - ID: admin@tumbleup.com, PW: Test1234!
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'admin@tumbleup.com', 'admin', '$2a$10$TyYEKdyDhnNJ9Ccrqw785e1Ho7ZOoHdmX2csBv1RYGq4dpgPFIjy2', 'Y');
-- MEMBER - ADMIN ROLE_CATEGORY
INSERT INTO "MEMBER_ROLE_CATEGORY"(MEMBER_ID, ROLE_CATEGORY_ID) 
VALUES(
    (SELECT ID FROM "MEMBER" WHERE EMAIL = 'admin@tumbleup.com'), 
    (SELECT ID FROM "ROLE_CATEGORY" WHERE NAME = 'all')
);

-- MEMBER - ID: cook, PW: test
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'cook@cook.com', '양과자점 플레지르', '$2a$10$ANWWqRFVxCrr4tqkzA/KB.JM6BnS.cqouOj995eNGJgPGkE366/CO', 'Y');

-- MEMBER - ID: art, PW: test
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'art@art.com', 'MUSIC&ART COMPANY', '$2a$10$ANWWqRFVxCrr4tqkzA/KB.JM6BnS.cqouOj995eNGJgPGkE366/CO', 'Y');

-- MEMBER - ID: book, PW: test
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'book@book.com', '맛있는 책방', '$2a$10$ANWWqRFVxCrr4tqkzA/KB.JM6BnS.cqouOj995eNGJgPGkE366/CO', 'Y');

-- MEMBER - ID: buyer1, PW: test
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'buyer1@buyer.com', '후원자1', '$2a$10$ANWWqRFVxCrr4tqkzA/KB.JM6BnS.cqouOj995eNGJgPGkE366/CO', 'Y');

-- MEMBER - ID: buyer2, PW: test
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'buyer2@buyer.com', '후원자2', '$2a$10$ANWWqRFVxCrr4tqkzA/KB.JM6BnS.cqouOj995eNGJgPGkE366/CO', 'Y');

-- MEMBER - ID: buyer3, PW: test
INSERT INTO "MEMBER"(ID, EMAIL, NICKNAME, PWD, IS_EMAIL_VERIFIED) 
VALUES(MEMBER_ID_SEQ.NEXTVAL, 'buyer3@buyer.com', '후원자3', '$2a$10$ANWWqRFVxCrr4tqkzA/KB.JM6BnS.cqouOj995eNGJgPGkE366/CO', 'Y');

-- ADMIN - dashboard statistics
insert into visitor_per_day (member_id, date_visited) values(1, trunc(sysdate)-1);
insert into visitor_per_day (member_id, date_visited) values(2, trunc(sysdate)-2);
insert into visitor_per_day (member_id, date_visited) values(1, trunc(sysdate)-3);
insert into visitor_per_day (member_id, date_visited) values(1, trunc(sysdate)-3
insert into visitor_count_per_day (count, date_visited) values(6, trunc(sysdate)-200);
insert into visitor_count_per_day (count, date_visited) values(3, trunc(sysdate)-75);
insert into visitor_count_per_day (count, date_visited) values(7, trunc(sysdate)-35);
insert into visitor_count_per_day (count, date_visited) values(4, trunc(sysdate)-15);
insert into visitor_count_per_day (count, date_visited) values(1, trunc(sysdate)-9);
insert into visitor_count_per_day (count, date_visited) values(3, trunc(sysdate)-8);
insert into visitor_count_per_day (count, date_visited) values(2, trunc(sysdate)-7);
insert into visitor_count_per_day (count, date_visited) values(6, trunc(sysdate)-6);
insert into visitor_count_per_day (count, date_visited) values(5, trunc(sysdate)-5);
insert into visitor_count_per_day (count, date_visited) values(16, trunc(sysdate)-4);
insert into visitor_count_per_day (count, date_visited) values(11, trunc(sysdate)-3);
insert into visitor_count_per_day (count, date_visited) values(26, trunc(sysdate)-2);
insert into visitor_count_per_day (count, date_visited) values(19, trunc(sysdate)-1);
insert into visitor_count_per_day (count, date_visited) values(36, trunc(sysdate)-0);

-- 프로젝트 작성
INSERT INTO "PROJECT"(
	ID, TITLE, SUB_TITLE, TARGET_AMOUNT, DATE_PROJECT_STARTED, DATE_PROJECT_CLOSED, HASHTAG, 
	THUMB_IMG, MAIN_IMG, SUMMARY, STORY, WRITER_NAME, WRITER_PROFILE_IMG, 
	WRITER_SNS_INSTAGRAM, WRITER_SNS_FACEBOOK, WRITER_PHONE, WRITER_EMAIL, 
	MEMBER_ID, PROJECT_CATEGORY_ID, PROJECT_STATUS_CATEGORY_ID
) 
VALUES(
	PROJECT_ID_SEQ.NEXTVAL, 
	'제목', '부제목', 1000, SYSDATE, SYSDATE, '베이커리, ㅇㅇ, ㅇㅇ',
	'/img/test.jpg', '/img/test.jpg', '요약', '본문', '작성자이름', '프로필 이미지',
	'http://google.com', 'http://google.com', '010-1234-1234', 'test@test.com',	
	(SELECT ID FROM "MEMBER" WHERE EMAIL = 'cook@cook.com'), '1', '1'
);
INSERT INTO "PROJECT"(
	ID, TITLE, SUB_TITLE, TARGET_AMOUNT, DATE_PROJECT_STARTED, DATE_PROJECT_CLOSED, HASHTAG, 
	THUMB_IMG, MAIN_IMG, SUMMARY, STORY, WRITER_NAME, WRITER_PROFILE_IMG, 
	WRITER_SNS_INSTAGRAM, WRITER_SNS_FACEBOOK, WRITER_PHONE, WRITER_EMAIL, 
	MEMBER_ID, PROJECT_CATEGORY_ID, PROJECT_STATUS_CATEGORY_ID
) 
VALUES(
	PROJECT_ID_SEQ.NEXTVAL, 
	'제목', '부제목', 1000, SYSDATE, SYSDATE, '베이커리, ㅇㅇ, ㅇㅇ',
	'/img/test.jpg', '/img/test.jpg', '요약', '본문', '작성자이름', '프로필 이미지',
	'http://google.com', 'http://google.com', '010-1234-1234', 'test@test.com',	
	(SELECT ID FROM "MEMBER" WHERE EMAIL = 'cook@cook.com'), '2', '1'
);
INSERT INTO "PROJECT"(
	ID, TITLE, SUB_TITLE, TARGET_AMOUNT, DATE_PROJECT_STARTED, DATE_PROJECT_CLOSED, HASHTAG, 
	THUMB_IMG, MAIN_IMG, SUMMARY, STORY, WRITER_NAME, WRITER_PROFILE_IMG, 
	WRITER_SNS_INSTAGRAM, WRITER_SNS_FACEBOOK, WRITER_PHONE, WRITER_EMAIL, 
	MEMBER_ID, PROJECT_CATEGORY_ID, PROJECT_STATUS_CATEGORY_ID
) 
VALUES(
	PROJECT_ID_SEQ.NEXTVAL, 
	'제목', '부제목', 1000, SYSDATE, SYSDATE, '베이커리, ㅇㅇ, ㅇㅇ',
	'/img/test.jpg', '/img/test.jpg', '요약', '본문', '작성자이름', '프로필 이미지',
	'http://google.com', 'http://google.com', '010-1234-1234', 'test@test.com',	
	(SELECT ID FROM "MEMBER" WHERE EMAIL = 'cook@cook.com'), '3', '1'
);

INSERT INTO "PROJECT"(
	ID, TITLE, SUB_TITLE, TARGET_AMOUNT, DATE_PROJECT_STARTED, DATE_PROJECT_CLOSED, HASHTAG, 
	THUMB_IMG, MAIN_IMG, SUMMARY, STORY, WRITER_NAME, WRITER_PROFILE_IMG, 
	WRITER_SNS_INSTAGRAM, WRITER_SNS_FACEBOOK, WRITER_PHONE, WRITER_EMAIL, 
	MEMBER_ID, PROJECT_CATEGORY_ID, PROJECT_STATUS_CATEGORY_ID
) 
VALUES(
	PROJECT_ID_SEQ.NEXTVAL, 
	'제목', '부제목', 1000, SYSDATE, SYSDATE, '베이커리, ㅇㅇ, ㅇㅇ',
	'/img/test.jpg', '/img/test.jpg', '요약', '본문', '작성자이름', '프로필 이미지',
	'http://google.com', 'http://google.com', '010-1234-1234', 'test@test.com',	
	(SELECT ID FROM "MEMBER" WHERE EMAIL = 'cook@cook.com'), '7', '1'
);

INSERT INTO "PROJECT"(
	ID, TITLE, SUB_TITLE, TARGET_AMOUNT, DATE_PROJECT_STARTED, DATE_PROJECT_CLOSED, HASHTAG, 
	THUMB_IMG, MAIN_IMG, SUMMARY, STORY, WRITER_NAME, WRITER_PROFILE_IMG, 
	WRITER_SNS_INSTAGRAM, WRITER_SNS_FACEBOOK, WRITER_PHONE, WRITER_EMAIL, 
	MEMBER_ID, PROJECT_CATEGORY_ID, PROJECT_STATUS_CATEGORY_ID
) 
VALUES(
	PROJECT_ID_SEQ.NEXTVAL, 
	'제목', '부제목', 1000, SYSDATE, SYSDATE, '베이커리, ㅇㅇ, ㅇㅇ',
	'/img/test.jpg', '/img/test.jpg', '요약', '본문', '작성자이름', '프로필 이미지',
	'http://google.com', 'http://google.com', '010-1234-1234', 'test@test.com',	
	(SELECT ID FROM "MEMBER" WHERE EMAIL = 'cook@cook.com'), '1', '1'
);

-- 리워드(상품) 종류 작성
INSERT INTO "REWARD"(
	ID, PRICE, NAME, DETAIL, MAX_STOCK, CURRENT_STOCK, IS_ADDRESS_REQUIRED, DATE_DELIVERY_ESTIMATED, 
	PROJECT_ID, OPTION_FORM
) 
VALUES(
	REWARD_ID_SEQ.NEXTVAL, 
	1000, 'NAME', 'DETAIL', 1000, 100, 'Y', SYSDATE,
	(SELECT max(ID) FROM "PROJECT"),
	''
);

-- 예약 작성
INSERT INTO "RESERVE"(
	ID, BILLINGKEY, ADDITIONAL_BILLINGS, DATE_CREATED, RECEIVER_NAME, RECEIVER_PHONE, RECEIVER_ADDRESS, REQUEST_FOR_DELIVERY, 
	RESERVE_STATUS_CATEGORY_ID, MEMBER_ID, PROJECT_ID
) 
VALUES(
	RESERVE_ID_SEQ.NEXTVAL, 
	'BILLINGKEY', 1000, SYSDATE, 'NAME', 01012341234, 
	'RECEIVER_ADDRESS', 'REQUEST_FOR_DELIVERY', 1, 
    (SELECT ID FROM "MEMBER" WHERE EMAIL = 'cook@cook.com'),
    (SELECT max(ID) FROM "PROJECT")
);

-- 예약 내역 작성
INSERT INTO "RESERVE_REWARD"(
	RESERVE_ID, REWARD_ID, REWARD_SUM
) 
VALUES(
	(SELECT max(ID) FROM "RESERVE"), 
	(SELECT max(ID) FROM "REWARD"), 
	2
);


-- notice
-- insert


-- faq
-- insert
															 
															 
															 
															 -- 프로젝트 리스트, 상세 페이지 테스트용 데이터 --------------------------------------------------------------------------------------
															
REM INSERTING into PROJECT
SET DEFINE OFF;
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'상큼한 재미가 팡팡 터지는 불릿 오렌지 확장','날아오는 총알을 팡팡! 개성 넘치는 네 명의 영웅이 전장에 합류합니다!',22000,to_date('21/04/14','RR/MM/DD'),to_date('21/04/26','RR/MM/DD'),'1','1','1','1','첫번째 프로젝트 스토리입니다.','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,1,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'컬러에 답은 없어도 예쁨은 있어, <배색카드100>','정답은 없지만 오답은 있는 컬러배색, 당신의 배색을 도와드립니다. <배색카드100>',200000,to_date('21/04/21','RR/MM/DD'),to_date('21/04/30','RR/MM/DD'),'1','2','2','2','두번째 프로젝트 스토리','hyogil','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),5,2,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'천사가 지구에 입국했다? 근데 이 녀석 좀 수상해!','<천사가 입국했다 vol.1> 만화책 제작 프로젝트입니다!',333333,to_date('21/04/28','RR/MM/DD'),to_date('21/05/13','RR/MM/DD'),'1','2','3','2','3333333333333333333333333333333333','hyogil','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),5,3,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'군생활, 자포자기가 아닌 성장의 기회로 <나라면 말이야>','사랑하는 나의 군인에게 기꺼이 멘토가 되어줄 군인성장에세이 ''나라면 말이야''',333333,to_date('21/04/14','RR/MM/DD'),to_date('21/05/10','RR/MM/DD'),'1','2','4','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,1,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'웹툰배경 건물외부와 내부셋트','웹툰에 필요한 건물의 내부와 외부를 모아보세요. 작가님의 작품 활동에 많은 도움이 됩니다.',333333,to_date('21/04/05','RR/MM/DD'),to_date('21/05/10','RR/MM/DD'),'1','2','5','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,2,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'당신의 로맨스 판타지를 위한 무기','로맨스 판타지에 유용하게 사용할 수 있는 무기들의 포즈집입니다.',333333,to_date('21/04/17','RR/MM/DD'),to_date('21/05/01','RR/MM/DD'),'1','2','6','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,5,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'사이버펑크X전통문화. 사펑 12간지 아트북 [사풍화첩]','사이버펑크와 전통문화가 고도로 발달한 ''사풍세계''의 십이지 인물들 이야기. <사풍화첩>',333333,to_date('21/04/19','RR/MM/DD'),to_date('21/05/26','RR/MM/DD'),'1','2','7','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,7,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'나를 정의 내리는 일, 단편영화 <BLUE>','서울예술대학교 졸업영화 <BLUE>',333333,to_date('21/03/25','RR/MM/DD'),to_date('21/05/13','RR/MM/DD'),'1','2','8','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,8,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'다른 세계의 수호신','한국의 사천왕과 사신수를 다른 세계에서 나를 지켜주는 수호신 일러스트로 그려봤습니다',333333,to_date('21/04/23','RR/MM/DD'),to_date('21/05/07','RR/MM/DD'),'1','2','9','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,3,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'인터넷 방송인 패션화보 <Broad> : Musician','TAG Production의 패션화보 "Broad" Musician호입니다.',333333,to_date('21/04/17','RR/MM/DD'),to_date('21/05/15','RR/MM/DD'),'1','2','10','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,6,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'달콤한 말, 아니 달콤한 향으로 ''유혹''해 <캔디 향수>','당신의 코를 마비시켜줄 앙큼한 유혹의 캔디향수. 슬라이퍼퓸',333333,to_date('21/04/02','RR/MM/DD'),to_date('21/05/30','RR/MM/DD'),'1','2','11','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,6,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'비영리독립언론 외대알리 35호, ''변화를 주도하는 청년들''','청년들의 목소리를 대변하는 비영리독립언론 외대알리가 35호를 발행합니다.',333333,to_date('21/05/18','RR/MM/DD'),to_date('21/06/17','RR/MM/DD'),'1','2','12','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,4,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'일상의 소소한 행복을 채우는 <하루,한입> 미션 다이어리','30일 간 매일 하나씩 미션을 수행하고, 나만의 스티커 아트로 일상의 행복을 채워보세요!',333333,to_date('21/04/26','RR/MM/DD'),to_date('21/05/23','RR/MM/DD'),'1','2','13','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,4,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'패션&라이프스타일 매거진 브레이크 27호: AWAKE','패션&라이프스타일 매거진 브레이크에서 27호 <AWAKE>을 발간합니다.',333333,to_date('21/04/28','RR/MM/DD'),to_date('21/05/13','RR/MM/DD'),'1','2','14','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,2,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'직접 창작한 브랜드 로고 & 패턴 이미지 웹툰 브러쉬','직접 창작 및 제작한 100종 이상의 브랜드 로고 브러쉬 입니다. 웹툰과 인쇄출력 라이센스',333333,to_date('21/05/02','RR/MM/DD'),to_date('21/05/13','RR/MM/DD'),'1','2','15','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,1,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'이별을 주제로 엮은 시집 : 꽃','이별을 주제로 80편의 시들을 엮은 운율 시집입니다.',333333,to_date('21/04/15','RR/MM/DD'),to_date('21/04/30','RR/MM/DD'),'1','2','16','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,5,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'여성의 몸을 잘 아는 간호사가 만든 Y존이 숨쉬는 사각팬티','림프절 순환을 막는 삼각팬티, 걸으면 말리는 드로즈 NO! 정혈대 부착이 가능한 사각팬티',333333,to_date('21/05/01','RR/MM/DD'),to_date('21/06/01','RR/MM/DD'),'1','2','17','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,11,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'"고기 없는 간식이 이렇게 맛있어?" 반려견 비건 간식','당뇨견 주니의 보호자이자 조리전공자+펫푸드전문가 주니누나가 연구한 친환경 반려견 비건 간식',333333,to_date('21/04/02','RR/MM/DD'),to_date('21/05/13','RR/MM/DD'),'1','2','18','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,3,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'변호사가 알려주는 성폭력 피해자를 위한 법률가이드','성폭력 피해 직후부터 재판에 이르기까지의 과정 동안 어떻게 대응해야 할지를 알려드립니다.',333333,to_date('21/04/23','RR/MM/DD'),to_date('21/05/08','RR/MM/DD'),'1','2','19','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,5,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'<스냅툰&스케치업> 중국풍 무협 사극 웹툰배경 2탄','<스냅툰X지노보노> 동양 무협배경2탄! 1탄도 스냅툰과 함께 업데이트 되었어요',333333,to_date('21/04/28','RR/MM/DD'),to_date('21/05/04','RR/MM/DD'),'1','2','20','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,12,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'[스케치업+클튜3D소재] 로판 티 세트&티 룸 패키지','로판 웹툰에서 쓰기 좋은 티세트&티룸 패키지 입니다. 스케치업과 클튜3D소재로 제공됩니다.',333333,to_date('21/04/30','RR/MM/DD'),to_date('21/05/02','RR/MM/DD'),'1','2','21','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,12,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'포근포근한 스니커즈를 굽다, <슈크림 & 베이글>','가족끼리 만든 포근한 스니커즈! 슈크림과 베이글을 소개합니다:)',333333,to_date('21/04/13','RR/MM/DD'),to_date('21/05/18','RR/MM/DD'),'1','2','22','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,11,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'이내 사랑에 빠져들 인디팝, 후하 첫 EP [Spring]','이상하게도 너무 선명한 어떤 계절들에 대해 노래하고 있는 후하의 첫 EP [Spring]',333333,to_date('21/04/26','RR/MM/DD'),to_date('21/05/13','RR/MM/DD'),'1','2','23','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,10,2);
Insert into PROJECT (ID,TITLE,SUB_TITLE,TARGET_AMOUNT,DATE_PROJECT_STARTED,DATE_PROJECT_CLOSED,HASHTAG,THUMB_IMG,MAIN_IMG,SUMMARY,STORY,WRITER_NAME,WRITER_PROFILE_IMG,WRITER_SNS_INSTAGRAM,WRITER_SNS_FACEBOOK,WRITER_PHONE,WRITER_EMAIL,DATE_CREATED,DATE_UPDATED,MEMBER_ID,PROJECT_CATEGORY_ID,PROJECT_STATUS_CATEGORY_ID) values (PROJECT_ID_SEQ.NEXTVAL,'어르신들을 봄, 레곰이 아이패드&노트북 파우치','어르신들의 봄을 기록하는 ''RECORD'' 프로젝트의 제품창작&제작을 위해 진행하게 되었어요',333333,to_date('21/04/23','RR/MM/DD'),to_date('21/06/09','RR/MM/DD'),'1','2','24','2','3333333333333333333333333333333333','admin','1','1','1','1','1',to_date('21/04/12','RR/MM/DD'),to_date('21/04/12','RR/MM/DD'),1,1,2);


REM INSERTING into REWARD
SET DEFINE OFF;
Insert into REWARD (ID,PRICE,NAME,DETAIL,MAX_STOCK,CURRENT_STOCK,IS_ADDRESS_REQUIRED,DATE_DELIVERY_ESTIMATED,PROJECT_ID,OPTION_FORM) values (1,3000,'reward1','This is reward1',100,99,'N',to_date('21/04/30','RR/MM/DD'),1,'1');
Insert into REWARD (ID,PRICE,NAME,DETAIL,MAX_STOCK,CURRENT_STOCK,IS_ADDRESS_REQUIRED,DATE_DELIVERY_ESTIMATED,PROJECT_ID,OPTION_FORM) values (2,10000,'reward2','This is reward2',100,98,'N',to_date('21/04/30','RR/MM/DD'),1,'1');
Insert into REWARD (ID,PRICE,NAME,DETAIL,MAX_STOCK,CURRENT_STOCK,IS_ADDRESS_REQUIRED,DATE_DELIVERY_ESTIMATED,PROJECT_ID,OPTION_FORM) values (3,5000,'상품1','상품1 입니다.',100,100,'N',to_date('21/04/30','RR/MM/DD'),2,'1');
Insert into REWARD (ID,PRICE,NAME,DETAIL,MAX_STOCK,CURRENT_STOCK,IS_ADDRESS_REQUIRED,DATE_DELIVERY_ESTIMATED,PROJECT_ID,OPTION_FORM) values (4,50000,'상품2','상품2 입니다.',100,98,'N',to_date('21/04/30','RR/MM/DD'),2,'1');


REM INSERTING into RESERVE
SET DEFINE OFF;
Insert into RESERVE (ID,BILLINGKEY,ADDITIONAL_BILLINGS,DATE_CREATED,RECEIVER_NAME,RECEIVER_PHONE,RECEIVER_ADDRESS,REQUEST_FOR_DELIVERY,RESERVE_STATUS_CATEGORY_ID,MEMBER_ID,PROJECT_ID) values (1,'1',1,to_date('21/04/26','RR/MM/DD'),'kim',1012341234,'123123123','good',1,5,1);
Insert into RESERVE (ID,BILLINGKEY,ADDITIONAL_BILLINGS,DATE_CREATED,RECEIVER_NAME,RECEIVER_PHONE,RECEIVER_ADDRESS,REQUEST_FOR_DELIVERY,RESERVE_STATUS_CATEGORY_ID,MEMBER_ID,PROJECT_ID) values (2,'1',1,to_date('21/04/26','RR/MM/DD'),'park',1012341234,'123123123','good',1,2,1);
Insert into RESERVE (ID,BILLINGKEY,ADDITIONAL_BILLINGS,DATE_CREATED,RECEIVER_NAME,RECEIVER_PHONE,RECEIVER_ADDRESS,REQUEST_FOR_DELIVERY,RESERVE_STATUS_CATEGORY_ID,MEMBER_ID,PROJECT_ID) values (3,'1',1,to_date('21/04/26','RR/MM/DD'),'Lee',1012341234,'123123123','good',1,3,1);
Insert into RESERVE (ID,BILLINGKEY,ADDITIONAL_BILLINGS,DATE_CREATED,RECEIVER_NAME,RECEIVER_PHONE,RECEIVER_ADDRESS,REQUEST_FOR_DELIVERY,RESERVE_STATUS_CATEGORY_ID,MEMBER_ID,PROJECT_ID) values (4,'1',1,to_date('21/04/26','RR/MM/DD'),'Lee',1012341234,'123123123','good',1,1,2);
Insert into RESERVE (ID,BILLINGKEY,ADDITIONAL_BILLINGS,DATE_CREATED,RECEIVER_NAME,RECEIVER_PHONE,RECEIVER_ADDRESS,REQUEST_FOR_DELIVERY,RESERVE_STATUS_CATEGORY_ID,MEMBER_ID,PROJECT_ID) values (5,'1',1,to_date('21/04/26','RR/MM/DD'),'Lee',1012341234,'123123123','good',1,2,2);


REM INSERTING into RESERVE_REWARD
SET DEFINE OFF;
Insert into RESERVE_REWARD (RESERVE_ID,REWARD_ID,REWARD_SUM) values (1,2,10000);
Insert into RESERVE_REWARD (RESERVE_ID,REWARD_ID,REWARD_SUM) values (2,2,10000);
Insert into RESERVE_REWARD (RESERVE_ID,REWARD_ID,REWARD_SUM) values (3,1,3000);
Insert into RESERVE_REWARD (RESERVE_ID,REWARD_ID,REWARD_SUM) values (4,4,50000);
Insert into RESERVE_REWARD (RESERVE_ID,REWARD_ID,REWARD_SUM) values (5,4,50000);


REM INSERTING into UPLOAD_FILE
SET DEFINE OFF;
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (1,'2.jpg','2.jpg',1,'jpg',1,to_date('21/04/12','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (2,'1.jpg','1.jpg',2,'jpg',1,to_date('21/04/12','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (3,'3.jpg','3.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (4,'4.jpg','4.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (5,'5.jpg','5.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (6,'6.jpg','6.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (7,'7.jpg','7.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (8,'8.jpg','8.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (9,'9.jpg','9.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (10,'10.jpg','10.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (11,'11.jpg','11.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (12,'12.jpg','12.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (13,'13.jpg','13.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (14,'14.jpg','14.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (15,'15.jpg','15.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (16,'16.jpg','16.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (17,'17.jpg','17.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (18,'18.jpg','18.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (19,'19.jpg','19.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (20,'20.jpg','20.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (21,'21.jpg','21.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (22,'22.jpg','22.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (23,'23.jpg','23.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));
Insert into UPLOAD_FILE (ID,UPLOAD_NAME,SAVE_NAME,FILE_SIZE,FILE_TYPE,MEMBER_ID,DATE_CREATED) values (24,'24.jpg','24.jpg',1,'jpg',1,to_date('21/04/27','RR/MM/DD'));

-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

-- COMMIT
COMMIT;