-- Q&A
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (28,'후원자','1020jjo@gmail.com','결재 및 취소 질문',TO_CLOB(q'[<p><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif;">텀블벅 후원이 끝나고 결재상태라 따러 취소가 불가능한 것 같습니다..</span><br style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif;"><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGoth]')
|| TO_CLOB(q'[ic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif;">이때, 통장 잔고가 없어서 결재 및 재결재 실패 시 후원이 자동 취소되는지 궁금합니다.</span><br></p>]'),'dualseries',to_date('21/04/27','RR/MM/DD'),'Y','N','N');
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (27,'후원자','ppuppuppu@naver.com','주소를 잘못적어가지고 물건이 잘못 배송이 됬어요',TO_CLOB(q'[<p><span style="color: rgb(34, 34, 34); font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif;">주소가 잘못되어 배송이 잘못되었으니 제 물건을 찾으러 잘못적은 주소에 사시는 분께 갔고 그 분은 없다고 하셨습니다.</span></p><p><span style="color: rgb(34, 34, 34); font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif; font-size: 1rem;">그리]')
|| TO_CLOB(q'[고 제가 다시 텀블벅에 문의를 넣었고 다시 구매를 할수 있다고 해서 구매할 생각입니다. 금액이 22000원 이라 비싸지는 않는데...</span></p><p><span style="color: rgb(34, 34, 34); font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif; font-size: 1rem;">이 금액은 누가 책임져야하는건가요...?</span><br></p><p><br></p>]'),'645622213124',to_date('21/04/27','RR/MM/DD'),'Y','N','N');
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (26,'후원자','happyyyy@naver.com','결제에 관한 질문',TO_CLOB(q'[<p><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif;">결제를 하려고하는데&nbsp;</span><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif; font-size: 1rem;">주소지가 입력이 안되네요 ㅠㅠㅠㅠㅠㅠ</span></p><p><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Go]')
|| TO_CLOB(q'[thic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif; font-size: 1rem;"><br></span></p><p><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif;">다른 결제방법도 시도해보고 여러폰을 이용해서도 결제를 시도햇는데 결제가 되지않아서요 ㅜㅜ</span><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &qu]')
|| TO_CLOB(q'[ot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif; font-size: 1rem;"><br></span><br></p>]'),'28382938183123234',to_date('21/04/27','RR/MM/DD'),'Y','N','N');
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (25,'창작자','bee11@gmail.com','텀블벅 홍보방법','<p><span style="font-family: &quot;Helvetica Neue&quot;, &quot;Apple SD Gothic Neo&quot;, 나눔고딕, NanumGothic, &quot;맑은 고딕&quot;, &quot;Malgun Gothic&quot;, 돋움, Dotum, sans-serif;">그리고 저는 어떤 뚜렷한 메시지나 포인트를 가진 프로젝트가 아니라 디자인과 스타일이 이렇다 저렇다 하는 성격의 프로젝트입니다. 그냥 가방 사진을 많이 보여주고 싶은데, 적당한 곳이 있을까요???&nbsp;</span><br></p>','bag1111111',to_date('21/04/27','RR/MM/DD'),'Y','Y','N');
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (24,'창작자','ramram@gmail.com','문의','<p>출간 전인도서만 가능한가요 ?</p>',null,to_date('21/04/27','RR/MM/DD'),'Y','N','N');
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (23,'후원자','jinguu12@hanmail.net','선물이 안왔어요','<p>보냈다고 하셨는데 저는 못받았어요</p>',null,to_date('21/04/27','RR/MM/DD'),'Y','Y','N');
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (22,'일반','jiji02222@naver.com','탈퇴를 못 찾겠어요','<p>탈퇴시켜주세요</p>',null,to_date('21/04/27','RR/MM/DD'),'Y','Y','N');
Insert into QNA (ID,HEADER,EMAIL,TITLE,CONTENT,PATH,DATE_CREATED,IS_CONSENT,IS_STATE,IS_DELETED) values (21,'창작자','mymail02@naver.com','공개검토를 미루고 싶습니다','<p>5월 12일에 공개검토 예정인데 준비 미흡으로 차후로 미루고 싶습니다</p>','redProject309',to_date('21/04/27','RR/MM/DD'),'Y','Y','N');
